arrowParens: avoid
singleQuote: true
bracketSpacing: true
endOfLine: lf
semi: false
tabWidth: 2
trailingComma: none
plugins:
  - prettier-plugin-svelte
overrides:
  - files: '*.svelte'
    options:
      parser: svelte
